---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1663928/public_html/restaurant/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp about.html $DEPLOYPATH
    - /bin/cp services.html $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH    
